### ISSUE TITLE
option to change "select country" label name

### ISSUE THREAD

**Issue by kotte94** [kapilkumar0037/ngx-countries-dropdown-demo#3]
in my project I have to change the label name, to make the field "required" , we usually add * after the label name, How to do this with this package

**Comment by kapilkumar0037** [comment]
Ok so you want to change the placeholder? label you can change library not providing any labels and as of now the select country text in not configurable. I will implement this change soon.
What is the version of library you using?

**Comment by kotte94** [comment]
Angular 18

**Comment by kapilkumar0037** [comment]
Hi @kotte94, you can use the latest version of library which have the option to change the placeholder. Use input property placeholderText 

Thanks,
Kapil

**Comment by kotte94** [comment]
Thanks a lot @kapilkumar
